import PropTypes from 'prop-types';
import { useTranslation } from 'react-i18next';

/**
 * "Generated by AI" badge with an optional regenerate button. Shown on every
 * AI-generated block — an honesty + judging signal that output is real.
 */
export default function AiTag({ onRegenerate, loading = false, model }) {
  const { t } = useTranslation();
  return (
    <div className="flex items-center gap-2 text-xs">
      <span className="inline-flex items-center gap-1 rounded-full bg-brand-50 px-2.5 py-1 font-medium text-brand-700 dark:bg-brand-950 dark:text-brand-300">
        <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
          <path d="M12 2l1.9 4.6L18.5 8.5 13.9 10.4 12 15l-1.9-4.6L5.5 8.5l4.6-1.9L12 2zm6 11l.9 2.2 2.2.9-2.2.9L18 20l-.9-2.1-2.2-.9 2.2-.9L18 13z" />
        </svg>
        {t('common.generatedByAi')}
        {model && <span className="hidden text-brand-500 sm:inline">· {model}</span>}
      </span>
      {onRegenerate && (
        <button
          onClick={onRegenerate}
          disabled={loading}
          className="inline-flex items-center gap-1 rounded-full px-2 py-1 text-ink-500 transition hover:bg-ink-100 disabled:opacity-50 dark:hover:bg-ink-800"
          title={t('common.regenerate')}
        >
          <svg
            viewBox="0 0 24 24"
            className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`}
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            aria-hidden="true"
          >
            <path d="M21 12a9 9 0 1 1-2.64-6.36M21 3v5h-5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          <span className="hidden sm:inline">{t('common.regenerate')}</span>
        </button>
      )}
    </div>
  );
}

AiTag.propTypes = {
  onRegenerate: PropTypes.func,
  loading: PropTypes.bool,
  model: PropTypes.string,
};
